# Change these first
owner: Carbonate-dev # Your GitHub organization or username, where this repository lives
repo: statuspage # The name of this repository

sites:
  - name: Website
    url: https://carbonate.dev
  - name: API (Prod)
    url: https://api.carbonate.dev/docs
  - name: API (Staging)
    url: https://api.staging.carbonate.dev/docs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.carbonate.dev
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/131012332?s=200&v=4
  themeUrl: https://raw.githubusercontent.com/Carbonate-dev/statuspage/master/assets/theme.css
  name: Carbonate Status Page
  introTitle: "**Carbonate** turns simple language driven instructions into end-to-end tests."
  introMessage: This page provides an update on the uptime of Carbonate and its associated systems.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://carbonate.dev
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
